WITH RECURSIVE TIME AS (
    SELECT 0 HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME
    WHERE HOUR < 23
)

SELECT A.HOUR, IFNULL(B.COUNT, 0) COUNT
FROM TIME A
LEFT JOIN (
    SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)) B
ON B.HOUR = A.HOUR