SELECT C.AUTHOR_ID, D.AUTHOR_NAME, C.CATEGORY, C.TOTAL_SALES
FROM (
    SELECT A.AUTHOR_ID, A.CATEGORY,
        SUM(B.SALES * A.PRICE) TOTAL_SALES
    FROM BOOK A
    JOIN BOOK_SALES B
    ON A.BOOK_ID = B.BOOK_ID
    WHERE B.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY A.AUTHOR_ID, A.CATEGORY) C
JOIN AUTHOR D
ON C.AUTHOR_ID = D.AUTHOR_ID
ORDER BY C.AUTHOR_ID, C.CATEGORY DESC