SELECT C.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW B
JOIN MEMBER_PROFILE C
ON B.MEMBER_ID = C.MEMBER_ID
WHERE C.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(A.REVIEW_MAX)
        FROM (
            SELECT COUNT(*) REVIEW_MAX
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) A
    )
    LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT