SELECT YEAR(B.SALES_DATE) `YEAR`,
    MONTH(B.SALES_DATE) `MONTH`,
    COUNT(DISTINCT B.USER_ID) `PUCHASED_USERS`,
    ROUND(COUNT(DISTINCT B.USER_ID) / (
        SELECT COUNT(USER_ID)
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021), 1) `PUCHASED_RATIO`
FROM (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021) A
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)
ORDER BY `YEAR`, `MONTH`