SELECT HISTORY_ID,
    FLOOR(D.DAILY_FEE * (100 - IFNULL(C.DISCOUNT_RATE, 0)) / 100 * (DATEDIFF(D.END_DATE, D.START_DATE) + 1)) FEE
FROM (
    SELECT A.CAR_TYPE, A.DAILY_FEE, B.*
    FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '트럭') D
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON D.CAR_TYPE = C.CAR_TYPE
    AND C.DURATION_TYPE = IF(DATEDIFF(D.END_DATE, D.START_DATE) + 1 >= 90, '90일 이상',
            IF(DATEDIFF(D.END_DATE, D.START_DATE) + 1 >= 30, '30일 이상',
                IF(DATEDIFF(D.END_DATE, D.START_DATE) + 1 >= 7, '7일 이상', NULL)))
ORDER BY FEE DESC, HISTORY_ID DESC