SELECT C.APNT_NO, C.PT_NAME, C.PT_NO, C.MCDP_CD, D.DR_NAME, C.APNT_YMD
FROM (
    SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, A.APNT_YMD, A.MDDR_ID
    FROM APPOINTMENT A
    JOIN PATIENT B
    ON A.PT_NO = B.PT_NO
    WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
        AND (A.APNT_CNCL_YN = 'N' OR A.APNT_CNCL_YMD IS NULL)
        AND A.MCDP_CD = 'CS') C
JOIN DOCTOR D
ON D.DR_ID = C.MDDR_ID
ORDER BY C.APNT_YMD